version: "3"
services:
  node:
    build: .
    command: "npm run start"
    working_dir: /usr/app
    environment: 
      - NODE_ENV=development
    expose:
      - "4321"
    ports:
      - "4321:4321"